# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carousel',
            table='carousel',
        ),
        migrations.AlterModelTable(
            name='classification',
            table='classification',
        ),
        migrations.AlterModelTable(
            name='distribution',
            table='distribution',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='pattern',
            table='pattern',
        ),
        migrations.AlterModelTable(
            name='shopping',
            table='shopping',
        ),
        migrations.AlterModelTable(
            name='static',
            table='static',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='usersession',
        ),
        migrations.AlterModelTable(
            name='usersite',
            table='usersite',
        ),
    ]
