# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180828_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_new',
            field=models.BooleanField(default=0),
        ),
    ]
