# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180830_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browse',
            old_name='goobs',
            new_name='goods',
        ),
    ]
