# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180830_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='default_site',
            field=models.BooleanField(default=True),
        ),
    ]
