# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_usersite_default_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='usersite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.UserSite'),
        ),
    ]
